### ISSUE TITLE
"included_entities" not regenerated

### ISSUE THREAD

**Issue by BornToDoStuff** [MicleBrick/ExplosionRegen#31] opened 2020-06-25 04:54 UTC
I have tried several entities but have been unsuccessful in getting the new feature "regenerating additional entities" to work. It is successfully regenerating armor stands but any entities beyond that seem to not function as intended.

I have included my config as a .txt just in case the actual issue is just that I have used my configuration file incorrectly.
[config.txt](https://github.com/MicleBrick/ExplosionRegen/files/4829137/config.txt)

**Comment by MicleBrick** [comment] 2020-06-25 16:27
That feature limits which entities regenerate, it does not add additional entities

**Comment by MicleBrick** [comment] 2020-06-25 16:28
Nevermind, looks like you're right about the expected behavior. I'll see if I can test it some time

**Comment by MicleBrick** [comment] 2020-07-25 16:37
Fixed in 4.0.0

**Closed by MicleBrick** 2020-07-25 16:37 UTC
