### ISSUE TITLE
 Could not pass event WorldSaveEvent to ExplosionRegen v2.0.0

### ISSUE THREAD

**Issue by mrnicedonovan** [MicleBrick/ExplosionRegen#7] opened 2019-05-25 13:19 UTC
[15:13:14] [Server thread/ERROR]: Could not pass event WorldSaveEvent to ExplosionRegen v2.0.0
org.bukkit.event.EventException: null
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:320) ~[spigot-1.14.1.jar:git-Spigot-03bd4b0-c45c0a9]
        at org.bukkit.plugin.RegisteredListener.callEvent(RegisteredListener.java:70) ~[spigot-1.14.1.jar:git-Spigot-03bd4b0-c45c0a9]
        at org.bukkit.plugin.SimplePluginManager.fireEvent(SimplePluginManager.java:520) [spigot-1.14.1.jar:git-Spigot-03bd4b0-c45c0a9]
        at org.bukkit.plugin.SimplePluginManager.callEvent(SimplePluginManager.java:505) [spigot-1.14.1.jar:git-Spigot-03bd4b0-c45c0a9]
        at net.minecraft.server.v1_14_R1.WorldServer.save(WorldServer.java:749) [spigot-1.14.1.jar:git-Spigot-03bd4b0-c45c0a9]
        at net.minecraft.server.v1_14_R1.MinecraftServer.saveChunks(MinecraftServer.java:636) [spigot-1.14.1.jar:git-Spigot-03bd4b0-c45c0a9]
        at net.minecraft.server.v1_14_R1.MinecraftServer.a(MinecraftServer.java:976) [spigot-1.14.1.jar:git-Spigot-03bd4b0-c45c0a9]
        at net.minecraft.server.v1_14_R1.MinecraftServer.run(MinecraftServer.java:801) [spigot-1.14.1.jar:git-Spigot-03bd4b0-c45c0a9]
        at java.lang.Thread.run(Unknown Source) [?:1.8.0_121]
Caused by: java.lang.NoClassDefFoundError: it/unimi/dsi/fastutil/objects/Object2IntOpenHashMap
        at net.starlegacy.explosionregen.WorldData.save(WorldData.java:104) ~[?:?]
        at net.starlegacy.explosionregen.ExplosionRegenPlugin.onWorldSave(ExplosionRegenPlugin.java:48) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_121]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.14.1.jar:git-Spigot-03bd4b0-c45c0a9]
        ... 8 more
Caused by: java.lang.ClassNotFoundException: it.unimi.dsi.fastutil.objects.Object2IntOpenHashMap
        at java.net.URLClassLoader.findClass(Unknown Source) ~[?:1.8.0_121]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:135) ~[spigot-1.14.1.jar:git-Spigot-03bd4b0-c45c0a9]
        at org.bukkit.plugin.java.PluginClassLoader.findClass(PluginClassLoader.java:81) ~[spigot-1.14.1.jar:git-Spigot-03bd4b0-c45c0a9]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
        at java.lang.ClassLoader.loadClass(Unknown Source) ~[?:1.8.0_121]
        at net.starlegacy.explosionregen.WorldData.save(WorldData.java:104) ~[?:?]
        at net.starlegacy.explosionregen.ExplosionRegenPlugin.onWorldSave(ExplosionRegenPlugin.java:48) ~[?:?]
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:1.8.0_121]
        at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source) ~[?:1.8.0_121]
        at java.lang.reflect.Method.invoke(Unknown Source) ~[?:1.8.0_121]
        at org.bukkit.plugin.java.JavaPluginLoader$1.execute(JavaPluginLoader.java:316) ~[spigot-1.14.1.jar:git-Spigot-03bd4b0-c45c0a9]

**Comment by MicleBrick** [comment] 2019-05-26 17:47
Very sorry but I am away from home until June 5th and will probably not be able to fix anything until then

**Comment by mrnicedonovan** [comment] 2019-05-26 18:31
No problem bud, I can wait! Goodluck on your journey away from home

**Comment by MicleBrick** [comment] 2019-06-15 04:04
Very sorry, I went on another vacation after this and forgot about it. Getting home tomorrow. However, I think the issue is that it's depending on a different FastUtils version. Perhaps it's because I developed against Paper and not Spigot but you're using Spigot. As a temporary fix you could just use Paper, I'll remove the dependency on that fastutils class though.

**Comment by MicleBrick** [comment] 2019-07-01 17:51
Should be fixed now.

**Closed by MicleBrick** 2019-07-01 17:51 UTC
